
services:
  app:
    image: joelnorrman/project-java-ee:app-latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/JavaEE
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
      - weatherapp
    networks:
      - backend

  weatherapp:
    image: joelnorrman/project-java-ee:weatherapp-latest
    build:
      context: ../../webservice/weatherapp
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:weatherapp;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - backend

  db:
    image: joelnorrman/project-java-ee:postgres-db-latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: JavaEE
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  javaee-db: